name: update-unified

on:
  schedule:
    - cron: '0 10 * * *'  # todos los días 10:00 UTC (~07:00 UYT)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        run: python scraper_unificado.py
      - name: Commit & push
        run: |
          git config user.name "actions-bot"
          git config user.email "actions-bot@example.com"
          git add unified.json
          git commit -m "chore: update unified.json [skip ci]" || echo "No changes"
          git push
